<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="people">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="person" type="PersonType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="GenderType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="M"/>
            <xs:enumeration value="F"/>
            <xs:enumeration value="UNKNOWN"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="PersonType">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="gender" type="GenderType"/>
            <xs:element name="childrenAmount" type="xs:integer" minOccurs="0"/>
            <xs:element name="siblingsAmount" type="xs:integer" minOccurs="0"/>

            <xs:element name="spouseRef" type="xs:IDREF" minOccurs="0"/>
            <xs:element name="fatherRef" type="xs:IDREF" minOccurs="0"/>
            <xs:element name="motherRef" type="xs:IDREF" minOccurs="0"/>

            <xs:element name="brothers" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="brotherRef" type="xs:IDREF" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="sisters" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="sisterRef" type="xs:IDREF" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="sons" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="sonRef" type="xs:IDREF" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="daughters" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="daughterRef" type="xs:IDREF" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>

        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
</xs:schema>